name: get-secretmanager-secrets Integration
on: [push]
jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./setup-gcloud
      with:
        service_account_email: ${{ secrets.SETUP_GCLOUD_IT_EMAIL }}
        service_account_key: ${{ secrets.SETUP_GCLOUD_IT_KEY_B64 }}
    - id: secrets
      uses: ./get-secretmanager-secrets
      with:
        secrets: |-
          token:${{ secrets.GET_SECRETMANAGER_SECRET_REF }}
    - name: get output
      run: echo '${{ steps.secrets.outputs.token }}'

  b64_json:
    name: with base64 json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: secrets
      uses: ./get-secretmanager-secrets
      with:
        credentials: ${{ secrets.SETUP_GCLOUD_IT_KEY_B64 }}
        secrets: |-
          token:${{ secrets.GET_SECRETMANAGER_SECRET_REF }}
    - name: get output
      run: echo '${{ steps.secrets.outputs.token }}'

  json:
    name: with json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: secrets
      uses: ./get-secretmanager-secrets
      with:
        credentials: ${{ secrets.SETUP_GCLOUD_IT_KEY }}
        secrets: |-
          token:${{ secrets.GET_SECRETMANAGER_SECRET_REF }}
    - name: get output
      run: echo '${{ steps.secrets.outputs.token }}'
