name: get-secretmanager-secrets Unit
on: [push, pull_request]
jobs:
  run:
    name: test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@master
      with:
        node-version: 12.x

    - run: npm install
      working-directory: ./get-secretmanager-secrets

    - run: npm test
      working-directory: ./get-secretmanager-secrets
